name: Terraform Workflow
on: workflow_dispatch
env:
  ARM_CLIENT_ID: ebb5c0b7-b108-4f09-9cbb-ac8fedec0ea7
  ARM_CLIENT_SECRET: rz58Q~5QEu13WWNFFhXui4ezR~tiY3bZG2.kJdqc
  ARM_SUBSCRIPTION_ID: 36255ad7-db1e-4d3b-81cc-d6b30072eee6
  ARM_TENANT_ID: ba2c3b37-5867-4630-8484-e171617286c4
  TF_LOG: TRACE
  working-directory: ./terraform
jobs:
 checkout:
  name: 'azure login'
  runs-on: ubuntu-latest
  steps:
  - name: Azure Login
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CLIENT_ID }} ${{ secrets.AZURE_CLIENT_SECRET }} ${{ secrets.AZURE_TENANT_ID }}
      sub: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #- name: Log in to azure
    #run: az login --service-principal --username "f15fb70e-6129-40f2-8f0a-66bb1045fc14" --password "lkH8Q~tG3KduKGRXkC4V~g4emEQWHie9wEmjYaDT" --tenant "ba2c3b37-5867-4630-8484-e171617286c4" || exit 1
