name: Terraform initialization
on: workflow_dispatch
env:
  ARM_CLIENT_ID: ebb5c0b7-b108-4f09-9cbb-ac8fedec0ea7
  ARM_CLIENT_SECRET: rz58Q~5QEu13WWNFFhXui4ezR~tiY3bZG2.kJdqc
  ARM_SUBSCRIPTION_ID: 36255ad7-db1e-4d3b-81cc-d6b30072eee6
  ARM_TENANT_ID: ba2c3b37-5867-4630-8484-e171617286c4

jobs:
 terraform_init:
  name: 'Terraform initialization'
  runs-on: ubuntu-latest
  steps:
  - name: checkout repository
    uses: actions/checkout@v4

  - name: terraform install
    uses: hashicorp/setup-terraform@v2.0.3
    
  - name: Terraform format
    run: |
     pwd
     ls -ltrh
     cd terraform
     terraform fmt
    
  - name: Terraform init
    run: | 
      ls -l
      cd terraform
      ls -l
      terraform init -input=false

  - name: Terraform validate
    run: terraform validate

 terraform_plan:
  name: 'Terraform Plan'
  runs-on: ubuntu-latest
  needs: [terraform_init]
  steps:
  - name: Terraform plan
    run: |
      cd terraform
      export exitcode=0
      terraform plan -detailed-exitcode -out planfile || export exitcode=$?
      echo "exitcode=$exitcode"        
      if [ $exitcode -eq 1 ]; then
      echo Terraform Plan Failed!
      exit 1
      else 
      exit 0
      fi
  
  - name: Publish Terraform Plan
    uses: actions/upload-artifact@v3
    with:
      name: planfile
      path: planfile
