name: Terraform initialization
on: workflow_dispatch
env:
  ARM_CLIENT_ID: ebb5c0b7-b108-4f09-9cbb-ac8fedec0ea7
  ARM_CLIENT_SECRET: rz58Q~5QEu13WWNFFhXui4ezR~tiY3bZG2.kJdqc
  ARM_SUBSCRIPTION_ID: 36255ad7-db1e-4d3b-81cc-d6b30072eee6
  ARM_TENANT_ID: ba2c3b37-5867-4630-8484-e171617286c4
  TF_LOG: TRACE
jobs:
 checkout:
  name: 'Terraform checkout'
  runs-on: ubuntu-latest
  steps:
  - name: checkout repository
    uses: actions/checkout@v4

 terraform_install:
  name: 'Terraform install'
  runs-on: ubuntu-latest
  needs: [checkout]
  steps:
  - name: terraform install
    uses: hashicorp/setup-terraform@v2.0.3

 terraform_format:
  name: 'Terraform format'
  runs-on: ubuntu-latest
  needs: [terraform_install]
  steps:  
  - name: Terraform format
    run: |
     pwd
     ls -ltrh
     cd terraform
     terraform fmt

 terraform_init:
  name: 'Terraform init'
  runs-on: ubuntu-latest
  needs: [terraform_install]
  steps:     
  - name: Terraform init
    run: | 
      ls -l
      cd terraform
      ls -l
      terraform init -input=false

 terraform_validate:
  name: 'Terraform validate'
  runs-on: ubuntu-latest
  needs: [terraform_install]
  steps:
  - name: Terraform validate
    run: terraform validate
    
  - name: Terraform plan
    run: |
      cd terraform
      ls -ltrh
      pwd
      export exitcode=0
      terraform plan -input=false -detailed-exitcode -out planfile || export exitcode=$?
      echo "exitcode=$exitcode"        
      if [ $exitcode -eq 1 ]; then
      echo Terraform Plan Failed!
      exit 1
      else 
      exit 0
      fi
  
  - name: Publish Terraform Plan
    uses: actions/upload-artifact@v3
    with:
      name: planfile
      path: planfile
